FROM golang:alpine as builder

WORKDIR /utils

COPY ./utils/tparse /utils/tparse
WORKDIR /utils/tparse
RUN CGO_ENABLED=0 GOOS=linux go build -o tparse .

FROM golang:alpine
COPY --from=builder /utils/tparse/tparse /usr/local/bin/tparse