FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o mortgage_calculator ./cmd/mortgage_calculator

FROM scratch
COPY --from=builder /app/mortgage_calculator /
COPY ./config/config.yml /config.yml
ENTRYPOINT ["/mortgage_calculator", "-config=./config.yml"]