FROM golang:1.23-alpine AS builder

WORKDIR /utils

COPY ./utils/tparse /utils/tparse
WORKDIR /utils/tparse
RUN CGO_ENABLED=0 GOOS=linux go build -o tparse .

FROM golang:1.21-alpine
COPY --from=builder /utils/tparse/tparse /usr/local/bin/tparse