FROM golang:1.23-alpine AS builder

WORKDIR /utils

COPY ./utils/golangci-lint /utils/golangci-lint
WORKDIR /utils/golangci-lint
RUN CGO_ENABLED=0 GOOS=linux go build -o golangci-lint ./cmd/golangci-lint

FROM golang:1.21-alpine
COPY --from=builder /utils/golangci-lint/golangci-lint /usr/local/bin/golangci-lint